<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>upk</AssemblyName>
    <RootNamespace>UltimateProcessKiller.Cli</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64;osx-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UltimateProcessKiller.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UltimateProcessKiller.Core\UltimateProcessKiller.Core.csproj" />
  </ItemGroup>

</Project>
